# Generated by Django 3.0.7 on 2020-07-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200612_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('start', models.CharField(max_length=100)),
                ('stop', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
