# Generated by Django 3.0.7 on 2020-07-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='slots',
        ),
    ]
