# Generated by Django 3.0.7 on 2020-07-03 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200703_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dt',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
