# Generated by Django 3.0.7 on 2020-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bookings_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='st',
            field=models.TextField(default='free'),
        ),
    ]
