# Generated by Django 3.0.7 on 2020-07-03 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bookings_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(default=datetime.date.today, unique=True, verbose_name='date')),
                ('lt', models.TextField()),
                ('st', models.TextField(default='free')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
