# Generated by Django 3.0.7 on 2020-07-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200704_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='peer',
            field=models.TextField(default='no'),
        ),
    ]
