# Generated by Django 3.0.7 on 2020-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_booking_peer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='peer',
            field=models.TextField(default='yes'),
        ),
    ]
